/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import AccesoDatos.ADExtras;
import javax.swing.JOptionPane;
import AccesoDatos.ADPassword;
import java.util.ArrayList;

/**
 *
 * @author Keylor
 */
public class Configuraciones extends javax.swing.JPanel {

private Menu menu = null;
    /**
     * Creates new form Configuraciones
     */
    public Configuraciones(Menu menu) {
        initComponents();
       this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContrasena = new javax.swing.JPanel();
        lbPassOld = new javax.swing.JLabel();
        lbPassNew = new javax.swing.JLabel();
        lbPassConfirmed = new javax.swing.JLabel();
        passOld = new javax.swing.JPasswordField();
        passNew = new javax.swing.JPasswordField();
        passOldConfirm = new javax.swing.JPasswordField();
        btnAplicarPass = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        panelAjustesAnuales = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        btnEjecutarPrimerIngreso = new javax.swing.JButton();
        lb2 = new javax.swing.JLabel();
        btnEjecutarActualizarEdad = new javax.swing.JButton();
        panelCreditos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Otros Ajustes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        panelContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio de Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panelContrasena.setOpaque(false);

        lbPassOld.setText("Contraseña Actual:");

        lbPassNew.setText("Nueva Contraseña:");

        lbPassConfirmed.setText("Confirme Contraseña:");

        btnAplicarPass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAplicarPass.setText("Aplicar cambios");
        btnAplicarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContrasenaLayout = new javax.swing.GroupLayout(panelContrasena);
        panelContrasena.setLayout(panelContrasenaLayout);
        panelContrasenaLayout.setHorizontalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContrasenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelContrasenaLayout.createSequentialGroup()
                                .addComponent(lbPassOld, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passOld))
                            .addGroup(panelContrasenaLayout.createSequentialGroup()
                                .addComponent(lbPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passNew, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContrasenaLayout.createSequentialGroup()
                                .addComponent(lbPassConfirmed, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passOldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelContrasenaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnAplicarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelContrasenaLayout.setVerticalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassOld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassConfirmed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passOldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAplicarPass)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 0, 0));
        btnRegresar.setText("<< Regresar");
        btnRegresar.setMaximumSize(new java.awt.Dimension(100, 35));
        btnRegresar.setMinimumSize(new java.awt.Dimension(100, 35));
        btnRegresar.setPreferredSize(new java.awt.Dimension(100, 35));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        panelAjustesAnuales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajustes anuales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panelAjustesAnuales.setOpaque(false);
        panelAjustesAnuales.setPreferredSize(new java.awt.Dimension(311, 203));

        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Deshacer el primer ingreso del anterior ciclo lectivo.");

        btnEjecutarPrimerIngreso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEjecutarPrimerIngreso.setText("Deshacer primer ingreso");
        btnEjecutarPrimerIngreso.setToolTipText("Utilice este botón al iniciar un nuevo ciclo lectivo.");
        btnEjecutarPrimerIngreso.setPreferredSize(new java.awt.Dimension(172, 35));
        btnEjecutarPrimerIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarPrimerIngresoActionPerformed(evt);
            }
        });

        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("Recalcular Edad (Fechas de Nacimiento)");

        btnEjecutarActualizarEdad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEjecutarActualizarEdad.setText("Actualizar edades");
        btnEjecutarActualizarEdad.setToolTipText("Utilice este botón para recalcular la edad basandose en la fecha de nacimiento.");
        btnEjecutarActualizarEdad.setMaximumSize(new java.awt.Dimension(172, 35));
        btnEjecutarActualizarEdad.setMinimumSize(new java.awt.Dimension(172, 35));
        btnEjecutarActualizarEdad.setPreferredSize(new java.awt.Dimension(172, 35));
        btnEjecutarActualizarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActualizarEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAjustesAnualesLayout = new javax.swing.GroupLayout(panelAjustesAnuales);
        panelAjustesAnuales.setLayout(panelAjustesAnualesLayout);
        panelAjustesAnualesLayout.setHorizontalGroup(
            panelAjustesAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesAnualesLayout.createSequentialGroup()
                .addGroup(panelAjustesAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAjustesAnualesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelAjustesAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEjecutarPrimerIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEjecutarActualizarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAjustesAnualesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAjustesAnualesLayout.setVerticalGroup(
            panelAjustesAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesAnualesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEjecutarPrimerIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEjecutarActualizarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCreditos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creditos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panelCreditos.setToolTipText("");
        panelCreditos.setMaximumSize(new java.awt.Dimension(311, 194));
        panelCreditos.setMinimumSize(new java.awt.Dimension(311, 194));
        panelCreditos.setOpaque(false);
        panelCreditos.setPreferredSize(new java.awt.Dimension(311, 194));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Software realizado durante el TCU 582");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Proyecto Interdisciplinario de Atención a la Salud");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Realizado por los estudiantes:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alejandra Anchía");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("David Olivas");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Keylor Vargas");

        javax.swing.GroupLayout panelCreditosLayout = new javax.swing.GroupLayout(panelCreditos);
        panelCreditos.setLayout(panelCreditosLayout);
        panelCreditosLayout.setHorizontalGroup(
            panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        panelCreditosLayout.setVerticalGroup(
            panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelAjustesAnuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAjustesAnuales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.intercambiarPaneles(0);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAplicarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarPassActionPerformed
        String pass = "";
        String passConfirm = "";
        Boolean estado;
        char[] passwordOld = passOld.getPassword();
        for (int i = 0; i < passwordOld.length; i++) {
            pass += passwordOld[i];
        }

        if (pass.isEmpty() == false) {
            estado = consultarUltimaContrasena(pass);
            if (estado == true) {
                pass = "";
                char[] passwordNew = passNew.getPassword();
                for (int i = 0; i < passwordNew.length; i++) {
                    pass += passwordNew[i];
                }
                char[] passwordConfirm = passOldConfirm.getPassword();
                for (int i = 0; i < passwordConfirm.length; i++) {
                    passConfirm += passwordConfirm[i];
                }
                if (pass.isEmpty() == false && passConfirm.isEmpty() == false && pass.equals(passConfirm) == true ) {
                    if (consultarListaContrasena(passConfirm)== false) {
                        
                        ADPassword pw = new ADPassword();
                        pw.insertarPassword(pass);
                        JOptionPane.showMessageDialog(null, "Se ingreso correctamente",
                                "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                         JOptionPane.showMessageDialog(null, "La nueva contraseÃ±a debe ser distinta a cualquier contraseÃ±a anterior",
                            "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                    }
                  
                } else {
                    JOptionPane.showMessageDialog(null, "La contraseÃ±a de confirmaciÃ³n debe ser igual ala nueva contraseÃ±a",
                            "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                }

            } else {

                JOptionPane.showMessageDialog(null, "ContraseÃ±a Actual Incorrecta",
                        "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Digite la ContraseÃ±a Actual",
                    "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAplicarPassActionPerformed

    private void btnEjecutarActualizarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActualizarEdadActionPerformed
        try {
             ADExtras access = new ADExtras();
             access.ActualizarEdades();
             JOptionPane.showMessageDialog(null, "Tarea Ejecutada.", "Exito!",  JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha presentado un error al realizar la tarea", "Error!",  JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_btnEjecutarActualizarEdadActionPerformed

    private void btnEjecutarPrimerIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarPrimerIngresoActionPerformed
        try {
             ADExtras access = new ADExtras();
             access.LimpiarPrimerIngreso();
             JOptionPane.showMessageDialog(null, "Tarea Ejecutada.", "Exito!",  JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha presentado un error al realizar la tarea", "Error!",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEjecutarPrimerIngresoActionPerformed

    public boolean consultarListaContrasena(String contrasena) {
        boolean password = false;
        ADPassword pw = new ADPassword();
        ArrayList<String> lista = pw.obtenerListaPassword();

        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).equals(contrasena)) {
                password = true;
            }

        }
        return password;

    }
    
       public boolean consultarUltimaContrasena(String contrasena) {
        String ultimaPass;
        boolean password = false;
        ADPassword pw = new ADPassword();
        ultimaPass = pw.obtenerPassword();

        if (ultimaPass.equals(contrasena)) {
            password = true;
        }
        return password;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarPass;
    private javax.swing.JButton btnEjecutarActualizarEdad;
    private javax.swing.JButton btnEjecutarPrimerIngreso;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbPassConfirmed;
    private javax.swing.JLabel lbPassNew;
    private javax.swing.JLabel lbPassOld;
    private javax.swing.JPanel panelAjustesAnuales;
    private javax.swing.JPanel panelContrasena;
    private javax.swing.JPanel panelCreditos;
    private javax.swing.JPasswordField passNew;
    private javax.swing.JPasswordField passOld;
    private javax.swing.JPasswordField passOldConfirm;
    // End of variables declaration//GEN-END:variables
}
