package Presentacion;

//<editor-fold defaultstate="collapsed" desc="Importaciones">
import AccesoDatos.ADDoctor;
import AccesoDatos.ADLugarAtencion;
import AccesoDatos.ADPoblacion;
import AccesoDatos.ADPracticante;
import AccesoDatos.ADTipoIdentificacion;
import Entidades.Doctor;
import Entidades.LugarAtencion;
import Entidades.Poblacion;
import Entidades.Practicante;
import Entidades.TipoIdentificacion;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
//</editor-fold>

public class PanelGenerico extends javax.swing.JPanel {

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables">
    private int tipoVentana = 0;
    private int accion = 0; //agregar(1) y modificar(2)
    private boolean eliminado = false;
    private boolean primeraVez = true;
    private Menu menu = null;
    //</editor-fold>
    
    /** Constructor
     * Crea un nuevo panel genérico con el tipo de ventana especificado
     * @param tipoVentana define lo que se va a mostrar en el panel
     * Si la ventana es para TipoId(1), Doctor(2), Practicante(3), Población(4) o Lugar de Atención(5)
     * @param menu ventana de donde se llama este panel
     */
    public PanelGenerico(int tipoVentana, Menu menu) {
        initComponents();
        this.menu = menu;
        this.tipoVentana = tipoVentana;
        centrarColumans();
        panelDatos.setVisible(false);
        switch (tipoVentana) {
            case 1: //TIpo id
                cambiarTitulo("Tipo de Identificación");
                btnCargarEliminados.setVisible(false);
                consultarTodosTipoId();
                break;
            case 2: //Doctor
                cambiarTitulo("Doctor");
                btnCargarEliminados.setVisible(true);
                consultarDoctoresActivos();
                break;
            case 3: //Practicante
                cambiarTitulo("Practicante");
                btnCargarEliminados.setVisible(true);
                consultarPracticantesActivos();
                break;
            case 4: //Población
                cambiarTitulo("Población");
                btnCargarEliminados.setVisible(false);
                consultarPoblaciones();
                break;
            case 5: //Lugar Atención
                cambiarTitulo("Lugar de Atención");
                btnCargarEliminados.setVisible(true);
                consultarLugaresActivos();
                break;
            default:
                break;
        }
        primeraVez = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarEliminados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblGenerica = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblVariable = new javax.swing.JLabel();
        txtVariable = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        rbBecado = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "titulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        setOpaque(false);

        btnCargarEliminados.setText("Cargar Eliminados");
        btnCargarEliminados.setMaximumSize(new java.awt.Dimension(135, 35));
        btnCargarEliminados.setMinimumSize(new java.awt.Dimension(135, 35));
        btnCargarEliminados.setPreferredSize(new java.awt.Dimension(135, 35));
        btnCargarEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarEliminadosActionPerformed(evt);
            }
        });

        TblGenerica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TblGenerica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Title 3", "Title4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblGenerica.getTableHeader().setReorderingAllowed(false);
        TblGenerica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblGenericaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblGenerica);

        btnAgregar.setText("Agregar Nuevo");
        btnAgregar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnAgregar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnAgregar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        panelDatos.setOpaque(false);

        lblNombre.setText("Nombre:");

        lblVariable.setText("Institución:");

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnGuardar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnGuardar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnDesactivar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnDesactivar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        rbBecado.setText("Becado");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblVariable))
                .addGap(51, 51, 51)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(txtVariable))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(rbBecado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVariable)
                    .addComponent(txtVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbBecado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegresar.setForeground(new java.awt.Color(255, 0, 0));
        btnRegresar.setText("<< Regresar");
        btnRegresar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnRegresar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnRegresar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargarEliminados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnCargarEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /** TblGenericaMouseClicked
     * Carga la información del item seleccionado para ser modificado
     * @param evt evento
     */
    private void TblGenericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblGenericaMouseClicked
        accion = 2;
        int indiceFila = TblGenerica.getSelectedRow();
        String texto = (TblGenerica.getValueAt(indiceFila, 1)).toString();
        panelDatos.setVisible(true);
        txtNombre.setText(texto);
        switch (tipoVentana) {
            case 1: //tipo id
                rbBecado.setVisible(false);
                btnDesactivar.setVisible(false);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                cambiarTituloPanelDatos("Modificar Tipo de Identificación");
                break;
            case 2: //doctor
                rbBecado.setVisible(false);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                cambiarTituloPanelDatos("Modificar Doctor");
                btnDesactivar.setVisible(true);
                break;
            case 3: //practicante
                rbBecado.setVisible(false);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                cambiarTituloPanelDatos("Modificar Practicante");
                btnDesactivar.setVisible(true);
                break;
            case 4: //población
                rbBecado.setVisible(true);
                lblVariable.setVisible(true);
                txtVariable.setVisible(true);
                cambiarTituloPanelDatos("Modificar Población");
                btnDesactivar.setVisible(false);
                txtVariable.setText((TblGenerica.getValueAt(indiceFila, 2)).toString());
                rbBecado.setSelected(false);
                if (((TblGenerica.getValueAt(indiceFila, 3)).toString()).equals("Si")) {
                    rbBecado.setSelected(true);
                }
                break;
            case 5: //lugar atención
                rbBecado.setVisible(false);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                cambiarTituloPanelDatos("Modificar Lugar de Atención");
                btnDesactivar.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_TblGenericaMouseClicked

    /** btnGuardarActionPerformed
     * Guarda un objeto nuevo o los cambios realizados a uno existente
     * @param evt evento
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        switch (tipoVentana) {
            case 1:
                //<editor-fold defaultstate="collapsed" desc="Tipo Id">
                ADTipoIdentificacion bdTipoId = new ADTipoIdentificacion();
                if (accion == 1) {//agregar
                    String nombre = txtNombre.getText().trim();
                    if (nombre.equals("") || nombre.equals(" ")) {
                        JOptionPane.showMessageDialog(null, "No puede dejar el nombre en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        bdTipoId.InsertarTipoIdentificacion(new TipoIdentificacion(0, nombre));
                    }
                } else if (accion == 2) {//modificar
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdTipoId.ModificarTipoIdentificacion(new TipoIdentificacion(num, txtNombre.getText().trim()));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                bdTipoId.ConsultarTipoIdentificacion(TblGenerica);
                break;
                //</editor-fold>
            case 2:
                //<editor-fold defaultstate="collapsed" desc="Doctor">
                ADDoctor bdDoctor = new ADDoctor();
                if (accion == 1) {//agregar
                    String nombre = txtNombre.getText();
                    if (nombre.equals("") || nombre.equals(" ")) {
                        JOptionPane.showMessageDialog(null, "No puede dejar el nombre en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        bdDoctor.insertarDoctor(new Doctor(0, nombre.trim(), false));
                    }
                } else if (accion == 2) {//modificar
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        boolean estado = false;
                        if ((TblGenerica.getValueAt(indiceFila, 2).equals("Inactivo"))) {
                            estado = true;
                        }
                        bdDoctor.ModificarDoctor(new Doctor(num, txtNombre.getText().trim(), estado));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                if (eliminado) {
                    bdDoctor.consultarDoctor(TblGenerica, true);
                } else {
                    bdDoctor.consultarDoctor(TblGenerica, false);
                }
                break;
                //</editor-fold>
            case 3:
                //<editor-fold defaultstate="collapsed" desc="Practicante">
                ADPracticante bdPracticante = new ADPracticante();
                if (accion == 1) {//agregar
                    String nombre = txtNombre.getText();
                    if (nombre.equals("") || nombre.equals(" ")) {
                        JOptionPane.showMessageDialog(null, "No puede dejar el nombre en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        bdPracticante.insertaPracticante(new Practicante(0, nombre.trim(), false));
                    }
                } else if (accion == 2) {//modificar
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        boolean estado = false;
                        if ((TblGenerica.getValueAt(indiceFila, 2).equals("Inactivo"))) {
                            estado = true;
                        }
                        bdPracticante.ModificarPracticante(new Practicante(num, txtNombre.getText().trim(), estado));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                if (eliminado) {
                    bdPracticante.consultarPracticante(TblGenerica, true);
                } else {
                    bdPracticante.consultarPracticante(TblGenerica, false);
                }
                break;
                //</editor-fold>
            case 4:
                //<editor-fold defaultstate="collapsed" desc="Población">
                ADPoblacion bdPoblacion = new ADPoblacion();
                if (accion == 1) {//agregar
                    String nombre = txtNombre.getText();
                    String institucion = txtVariable.getText();
                    if (nombre.equals("") || nombre.equals(" ") || institucion.equals("") || institucion.equals(" ")) {
                        JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        bdPoblacion.InsertarPoblacion(new Poblacion(0, nombre.trim(), institucion.trim(), rbBecado.isSelected()));
                    }
                } else if (accion == 2) {//modificar
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        String nombre = txtNombre.getText();
                        String institucion = txtVariable.getText();
                        if (nombre.equals("") || nombre.equals(" ") || institucion.equals("") || institucion.equals(" ")) {
                            JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
                        } else {
                            bdPoblacion.ModificarPoblacion(new Poblacion(num, nombre.trim(), institucion.trim(), rbBecado.isSelected()));
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                bdPoblacion.consultarPoblacion(TblGenerica);
                break;
                //</editor-fold>
            case 5:
                //<editor-fold defaultstate="collapsed" desc="Lugar Atención">
                ADLugarAtencion bdLugar = new ADLugarAtencion();
                if (accion == 1) {//agregar
                    String nombre = txtNombre.getText();
                    if (nombre.equals("") || nombre.equals(" ")) {
                        JOptionPane.showMessageDialog(null, "No puede dejar el nombre en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                        bdLugar.insertarLugarAtencion(new LugarAtencion(0, nombre.trim(), false));
                    }
                } else if (accion == 2) {//modificar
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        boolean estado = false;
                        if ((TblGenerica.getValueAt(indiceFila, 2).equals("Inactivo"))) {
                            estado = true;
                        }
                        bdLugar.ModificarLugarAtencion(new LugarAtencion(num, txtNombre.getText().trim(), estado));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                if (eliminado) {
                    bdLugar.ConsultarLugaresAtención(TblGenerica, true);
                } else {
                    bdLugar.ConsultarLugaresAtención(TblGenerica, false);
                }
                break;
                //</editor-fold>
            default:
                break;
        }
        txtNombre.setText("");
        panelDatos.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /** btnAgregarActionPerformed
     * Carga el panel para ingresar la información para agregar un objeto nuevo
     * @param evt evento
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        accion = 1;
        TblGenerica.clearSelection();
        rbBecado.setVisible(false);
        switch (tipoVentana) {
            case 1: //tipo id
                panelDatos.setVisible(true);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                btnDesactivar.setVisible(false);
                txtNombre.setText("");
                cambiarTituloPanelDatos("Nuevo Tipo de Identificación");
                break;
            case 2: //doctor
                panelDatos.setVisible(true);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                txtNombre.setText("");
                cambiarTituloPanelDatos("Nuevo Doctor");
                btnDesactivar.setVisible(false);
                break;
            case 3: //practicante
                panelDatos.setVisible(true);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                txtNombre.setText("");
                cambiarTituloPanelDatos("Nuevo Practicante");
                btnDesactivar.setVisible(false);
                rbBecado.setSelected(false);
                break;
            case 4: //poblacion
                panelDatos.setVisible(true);
                lblVariable.setVisible(true);
                txtVariable.setVisible(true);
                txtNombre.setText("");
                txtVariable.setText("");
                cambiarTituloPanelDatos("Nueva Población");
                rbBecado.setVisible(true);
                btnDesactivar.setVisible(false);
                rbBecado.setSelected(false);
                break;
            case 5: //lugar atención
                panelDatos.setVisible(true);
                lblVariable.setVisible(false);
                txtVariable.setVisible(false);
                txtNombre.setText("");
                cambiarTituloPanelDatos("Nueva Lugar de Atención");
                btnDesactivar.setVisible(false);
                break;
            default:
                break;
        }
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /** btnDesactivarActionPerformed
     * Cambia el estado del objeto dependiendo del estado en que esté (eliminado o Activo)
     * @param evt evento
     */
    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        switch(tipoVentana) {
            case 1: //Tipo id
                //nada
                break;
            case 2:
                //<editor-fold defaultstate="collapsed" desc="Doctor">
                ADDoctor bdDoctor = new ADDoctor();
                if (eliminado) {
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdDoctor.ModificarDoctor(new Doctor(num, txtNombre.getText(), false));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    bdDoctor.consultarDoctor(TblGenerica, true);
                } else {
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdDoctor.ModificarDoctor(new Doctor(num, txtNombre.getText(), true));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    bdDoctor.consultarDoctor(TblGenerica, false);
                }
                break;
                //</editor-fold>
            case 3:
                //<editor-fold defaultstate="collapsed" desc="Practicante">
                ADPracticante bdPracticante = new ADPracticante();
                if (eliminado) {
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdPracticante.ModificarPracticante(new Practicante(num, txtNombre.getText(), false));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    bdPracticante.consultarPracticante(TblGenerica, true);
                } else {
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdPracticante.ModificarPracticante(new Practicante(num, txtNombre.getText(), true));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    bdPracticante.consultarPracticante(TblGenerica, false);
                }
                break;
                //</editor-fold>
            case 4: //población
                //nada
                break;
            case 5:
                //<editor-fold defaultstate="collapsed" desc="Lugar de Atención">
                ADLugarAtencion bdLugar = new ADLugarAtencion();
                if (eliminado) {
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdLugar.ModificarLugarAtencion(new LugarAtencion(num, txtNombre.getText(), false));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    bdLugar.ConsultarLugaresAtención(TblGenerica, true);
                } else {
                    int indiceFila = TblGenerica.getSelectedRow();
                    if (indiceFila >= 0) {
                        int num = (int) TblGenerica.getValueAt(indiceFila, 0);
                        bdLugar.ModificarLugarAtencion(new LugarAtencion(num, txtNombre.getText(), true));
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un item.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    bdLugar.ConsultarLugaresAtención(TblGenerica, false);
                }
                break;
                //</editor-fold>
            default:
                break;
        }
        panelDatos.setVisible(false);
    }//GEN-LAST:event_btnDesactivarActionPerformed

    /** btnCargarEliminadosActionPerformed
     * Carga los objetos en estado eliminado y los muestra enuna tabla
     * @param evt evento
     */
    private void btnCargarEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarEliminadosActionPerformed
        switch(tipoVentana) {
            case 1: //Tipo id
                //nada
                break;
            case 2: //Doctor
                if (eliminado) {
                    consultarDoctoresActivos();
                    btnCargarEliminados.setText("Cargar Eliminados");
                    txtNombre.setText("");
                } else {
                    consultarDoctoresEliminados();
                    btnCargarEliminados.setText("Cargar Activos");
                    txtNombre.setText("");
                }
                break;
            case 3: // Practicante
                if (eliminado) {
                    consultarPracticantesActivos();
                    btnCargarEliminados.setText("Cargar Eliminados");
                    txtNombre.setText("");
                } else {
                    consultarPracticantesEliminados();
                    btnCargarEliminados.setText("Cargar Activos");
                    txtNombre.setText("");
                }
                break;
            case 4: // Población
                //nada
                break;
            case 5: // Lugar de Atención
                if (eliminado) {
                    consultarLugaresActivos();
                    btnCargarEliminados.setText("Cargar Eliminados");
                    txtNombre.setText("");
                } else {
                    consultarLugaresEliminados();
                    btnCargarEliminados.setText("Cargar Activos");
                    txtNombre.setText("");
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnCargarEliminadosActionPerformed

    /** btnRegresarActionPerformed
     * Regresa al menu principal
     * @param evt evento
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.intercambiarPaneles(0);
    }//GEN-LAST:event_btnRegresarActionPerformed

    //<editor-fold defaultstate="collapsed" desc="Mis Métodos">
    
    /** consultarTodosTipoId
     * Consulta los tipos de id existentes y los carga en la tabla genérica
     */
    private void consultarTodosTipoId() {
        TableColumn column = TblGenerica.getColumn("Title 3");
        TblGenerica.removeColumn(column);
        TableColumn column2 = TblGenerica.getColumn("Title4");
        TblGenerica.removeColumn(column2);
        ADTipoIdentificacion bd = new ADTipoIdentificacion();
        bd.ConsultarTipoIdentificacion(TblGenerica);
    }
    
    /** consultarDoctoresActivos
     * Consulta los doctores activos existentes y los carga en la tabla genérica
     */
    private void consultarDoctoresActivos() {
        if (primeraVez) {
            TableColumn column = TblGenerica.getColumn("Title 3");
            TblGenerica.removeColumn(column);
            column.setHeaderValue("Estado");//Eliminado
            TblGenerica.addColumn(column);
            TableColumn column2 = TblGenerica.getColumn("Title4");
            TblGenerica.removeColumn(column2);
        }
        ADDoctor bd = new ADDoctor();
        bd.consultarDoctor(TblGenerica, false);
        eliminado = false;
        btnDesactivar.setText("Eliminar");
    }
    
    /** consultarDoctoresEliminados
     * Consulta los doctores eliminados existentes y los carga en la tabla genérica
     */
    private void consultarDoctoresEliminados() {
        ADDoctor bd = new ADDoctor();
        bd.consultarDoctor(TblGenerica, true);
        eliminado = true;
        btnDesactivar.setText("Activar");
    }
    
    /** consultarPracticantesActivos
     * Consulta los practicantes activos existentes y los carga en la tabla genérica
     */
    private void consultarPracticantesActivos() {
        if (primeraVez) {
            TableColumn column = TblGenerica.getColumn("Title 3");
            TblGenerica.removeColumn(column);
            column.setHeaderValue("Estado");//Eliminado
            TblGenerica.addColumn(column);
            TableColumn column2 = TblGenerica.getColumn("Title4");
            TblGenerica.removeColumn(column2);
        }
        ADPracticante bd = new ADPracticante();
        bd.consultarPracticante(TblGenerica, false);
        eliminado = false;
        btnDesactivar.setText("Eliminar");
    }
    
    /** consultarPracticantesEliminados
     * Consulta los practicantes eliminados existentes y los carga en la tabla genérica
     */
    private void consultarPracticantesEliminados() {
        ADPracticante bd = new ADPracticante();
        bd.consultarPracticante(TblGenerica, true);
        eliminado = true;
        btnDesactivar.setText("Activar");
        //bd.consultarPracticante(TblGenerica);
    }
    
    /** consultarPoblaciones
     * Consulta las poblaciones existentes y los carga en la tabla genérica
     */
    private void consultarPoblaciones() {
        TableColumn column = TblGenerica.getColumn("Title 3");
        TblGenerica.removeColumn(column);
        column.setHeaderValue("Institución");
        TblGenerica.addColumn(column);
        
        TableColumn column2 = TblGenerica.getColumn("Title4");
        TblGenerica.removeColumn(column2);
        column2.setHeaderValue("Becado");//Ver si es necesario incluirlo en la tabla
        TblGenerica.addColumn(column2);
        
        ADPoblacion bd = new ADPoblacion();
        bd.consultarPoblacion(TblGenerica);
    }
    
    /** consultarLugaresActivos
     * Consulta los lugares de atención activos existentes y los carga en la tabla genérica
     */
    private void consultarLugaresActivos() {
        if (primeraVez) {
            TableColumn column = TblGenerica.getColumn("Title 3");
            TblGenerica.removeColumn(column);
            column.setHeaderValue("Estado");//Eliminado
            TblGenerica.addColumn(column);
            TableColumn column2 = TblGenerica.getColumn("Title4");
            TblGenerica.removeColumn(column2);
        }
        ADLugarAtencion bd = new ADLugarAtencion();
        bd.ConsultarLugaresAtención(TblGenerica, false);
        eliminado = false;
        btnDesactivar.setText("Eliminar");
    }
    
    /** consultarLugaresEliminados
     * Consulta los lugares de atención eliminados existentes y los carga en la tabla genérica
     */
    private void consultarLugaresEliminados() {
        ADLugarAtencion bd = new ADLugarAtencion();
        bd.ConsultarLugaresAtención(TblGenerica, true);
        eliminado = true;
        btnDesactivar.setText("Activar");
    }
    
    /** centrarColumans
     * Centra los valores dentro de las celdas de la tabla genérica
     */
    private void centrarColumans() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TblGenerica.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        TblGenerica.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        TblGenerica.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        TblGenerica.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }
    
    /** cambiarTituloPanelDatos
     * cambia el título del panel de datos
     * @param titulo nuevo título a mostrar
     */
    private void cambiarTituloPanelDatos(String titulo) {
        TitledBorder border = BorderFactory.createTitledBorder(titulo);
        border.setTitleFont(new Font("Dialog", Font.BOLD, 12));
        panelDatos.setBorder(border);
    }
    
    /** cambiarTitulo
     * cambia el título del panel genérico
     * @param titulo nuevo título a mostrar
     */
    private void cambiarTitulo(String titulo) {
        TitledBorder border = BorderFactory.createTitledBorder(titulo);
        border.setTitleFont(new Font("Dialog", Font.BOLD, 14));
        this.setBorder(border);
    }

    //</editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblGenerica;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCargarEliminados;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVariable;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JRadioButton rbBecado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVariable;
    // End of variables declaration//GEN-END:variables
}