/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Keylor
 */
public class Tareas_Basicas extends javax.swing.JPanel {
    
    CargarInforme ori;

    /**
     * Creates new form Tareas_Basicas
     */
    public Tareas_Basicas(CargarInforme origen) {
        initComponents();
        ori = origen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_GastoProcPac = new javax.swing.JButton();
        btn_GastoProcPac1 = new javax.swing.JButton();
        btn_GastoProcPac2 = new javax.swing.JButton();
        btn_GastoProcPac3 = new javax.swing.JButton();
        btn_GastoProcPac4 = new javax.swing.JButton();
        btn_GastoProcPac5 = new javax.swing.JButton();
        btn_GastoProcPac6 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione el informe a trabajar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(978, 100));
        setMinimumSize(new java.awt.Dimension(978, 100));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(978, 100));

        btn_GastoProcPac.setText("Gasto y procedimientos por paciente");
        btn_GastoProcPac.setMaximumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac.setMinimumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac.setPreferredSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GastoProcPacActionPerformed(evt);
            }
        });

        btn_GastoProcPac1.setText("Actividades clinicas anuales");
        btn_GastoProcPac1.setMaximumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac1.setMinimumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac1.setPreferredSize(new java.awt.Dimension(235, 30));

        btn_GastoProcPac2.setText("Atención a pacientes");
        btn_GastoProcPac2.setMaximumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac2.setMinimumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac2.setPreferredSize(new java.awt.Dimension(235, 30));

        btn_GastoProcPac3.setText("Monto de atención a Pacientes");
        btn_GastoProcPac3.setMaximumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac3.setMinimumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac3.setPreferredSize(new java.awt.Dimension(240, 35));

        btn_GastoProcPac4.setText("Aplicaciones de procedimientos");
        btn_GastoProcPac4.setMaximumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac4.setMinimumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac4.setPreferredSize(new java.awt.Dimension(235, 30));

        btn_GastoProcPac5.setText("Frecuencia de atenciones de pacientes");
        btn_GastoProcPac5.setMaximumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac5.setMinimumSize(new java.awt.Dimension(235, 30));
        btn_GastoProcPac5.setPreferredSize(new java.awt.Dimension(235, 30));

        btn_GastoProcPac6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_GastoProcPac6.setForeground(new java.awt.Color(255, 0, 0));
        btn_GastoProcPac6.setText("<< Regresar");
        btn_GastoProcPac6.setMaximumSize(new java.awt.Dimension(150, 50));
        btn_GastoProcPac6.setMinimumSize(new java.awt.Dimension(150, 50));
        btn_GastoProcPac6.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_GastoProcPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_GastoProcPac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_GastoProcPac2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_GastoProcPac3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_GastoProcPac4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_GastoProcPac5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(btn_GastoProcPac6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_GastoProcPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btn_GastoProcPac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_GastoProcPac4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_GastoProcPac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_GastoProcPac5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_GastoProcPac3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_GastoProcPac6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GastoProcPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GastoProcPacActionPerformed
        ori.cargarTareaEspecifica(1);
    }//GEN-LAST:event_btn_GastoProcPacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GastoProcPac;
    private javax.swing.JButton btn_GastoProcPac1;
    private javax.swing.JButton btn_GastoProcPac2;
    private javax.swing.JButton btn_GastoProcPac3;
    private javax.swing.JButton btn_GastoProcPac4;
    private javax.swing.JButton btn_GastoProcPac5;
    private javax.swing.JButton btn_GastoProcPac6;
    // End of variables declaration//GEN-END:variables
}
