/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;
import AccesoDatos.ADPassword;

/**
 *
 * @author Alejandra
 */
public class VBloqueo extends javax.swing.JDialog {

    /**
     * Creates new form VBloqueo
     */
    public VBloqueo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        aplicarTema();
        this.setSize(375, 485);
        this.setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                Object[] options = {"Continuar", "Cerrar"};
                int n = JOptionPane.showOptionDialog(null, "Digite la contraseña.\n Si sale el sistema se Cerrara", "Confirmación",
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                if (n == JOptionPane.YES_OPTION) {
                } else if (n == JOptionPane.NO_OPTION) {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBienvenido = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jBAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLBienvenido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLBienvenido.setText("Bienvenidos");

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ico.png"))); // NOI18N

        jLContraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLContraseña.setText("Contraseña:");

        jBAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLContraseña))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(jLBienvenido))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLImagen))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBAceptar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBienvenido)
                .addGap(18, 18, 18)
                .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContraseña)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBAceptar)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
        String pass = "";
        Boolean estado;
        char[] password = jPassword.getPassword();
        for (int i = 0; i < password.length; i++) {
            pass += password[i];

        }
        if (pass.isEmpty() == false) {

            estado = consultarContrasena(pass);
            if (estado == true) {
                setVisible(false);
            } else {

                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta",
                        "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Digite la Contraseña",
                    "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jBAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean consultarContrasena(String contrasena) {
        boolean password = false;
        ADPassword pw = new ADPassword();
        ArrayList<String> lista = pw.obtenerPassword();

        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).equals(contrasena)) {
                password = true;
            }

        }
        return password;

    }

    private void aplicarTema() {
        setLocationRelativeTo(null);
        JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.OfficeBlue2007Skin");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JLabel jLBienvenido;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
